import csv
import os
from decimal import Decimal

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (Paragraph, SimpleDocTemplate, Spacer, Table,
                                TableStyle)

ROOT = os.path.join(
    os.path.dirname(__file__), "..", "outputs", "Training_Facility_Drawings_v1.1"
)
DATA_DIR = os.path.join(ROOT, "Data")
PDFS_DIR = os.path.join(ROOT, "PDFs")
os.makedirs(PDFS_DIR, exist_ok=True)


def sum_csv(fname):
    path = os.path.join(DATA_DIR, fname)
    total = Decimal("0")
    maint = Decimal("0")
    if not os.path.exists(path):
        return total, maint
    with open(path, newline="", encoding="utf-8") as f:
        r = csv.DictReader(f)
        for row in r:
            try:
                total += Decimal(str(row.get("TotalCost") or "0"))
            except Exception:
                pass
            try:
                maint += Decimal(str(row.get("MaintenanceAnnual") or "0"))
            except Exception:
                pass
    return total, maint


def build_pdf(out_path: str):
    ess, ess_maint = sum_csv("essential_equipment.csv")
    non, non_maint = sum_csv("nonessential_equipment.csv")
    furn, furn_maint = sum_csv("furniture_list.csv")
    maint_placeholder = Decimal("8500")
    grand = ess + non + furn + maint_placeholder

    doc = SimpleDocTemplate(out_path, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    story.append(
        Paragraph("Total Facility Cost Estimate — Plain Summary", styles["Title"])
    )
    story.append(Spacer(1, 12))

    data = [
        ["Category", "Subtotal (USD)"],
        ["Essential equipment", f"${ess:,.2f}"],
        ["Non-essential equipment", f"${non:,.2f}"],
        ["Furniture", f"${furn:,.2f}"],
        ["Maintenance (explicit sum)", f"${(ess_maint + non_maint + furn_maint):,.2f}"],
        ["Maintenance (placeholder applied)", f"${maint_placeholder:,.2f}"],
        [
            "Grand total (construction + furniture + placeholder maintenance)",
            f"${grand:,.2f}",
        ],
    ]

    table = Table(data, colWidths=[320, 160])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ]
        )
    )
    story.append(table)
    story.append(Spacer(1, 12))

    note = (
        "This PDF is an autogenerated plain-text summary page added to make the authoritative totals easily searchable. "
        "Refer to the CSV files in `Data/` for full line-item detail and to `checksums.sha256` for integrity verification."
    )
    story.append(Paragraph(note, styles["Normal"]))

    doc.build(story)


if __name__ == "__main__":
    out = os.path.join(PDFS_DIR, "Total_Facility_Cost_Estimate_plaintext.pdf")
    build_pdf(out)
    print("Wrote", out)
