#!/usr/bin/env python3
"""Download a PR .patch and extract @@ hunk headers for target files.

Writes `.github/pr_body_with_hunks.md` listing per-file anchors like
`path/to/file.py#Lstart-Lend` so reviewers can jump to changed lines.

Usage:
  python .github/parse_pr_patch_hunks.py [--pr N] [--url URL]

By default it fetches PR #13 for the repository '73junito/Combination-Automotive-Diesel-Mechanics-Facility'.
The script is intentionally dependency-free (uses stdlib only).
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
from typing import Dict, List, Tuple

DEFAULT_OWNER = "73junito"
DEFAULT_REPO = "Combination-Automotive-Diesel-Mechanics-Facility"
DEFAULT_PR = 13

TARGET_FILES = [
    "Combination_Automotive_Diesel_Facility_Project/Python_Workflow/scripts/assemble_facility.py",
    "Combination_Automotive_Diesel_Facility_Project/Python_Workflow/scripts/write_labels_to_dxf.py",
    "Combination_Automotive_Diesel_Facility_Project/Python_Workflow/scripts/append_legend_to_pdf.py",
    "Combination_Automotive_Diesel_Facility_Project/Python_Workflow/scripts/generate_legend_pdf.py",
    "Combination_Automotive_Diesel_Facility_Project/Python_Workflow/scripts/equipment_bay_mapper.py",
    "Combination_Automotive_Diesel_Facility_Project/Python_Workflow/scripts/replace_labels_with_blocks.py",
    "Combination_Automotive_Diesel_Facility_Project/Python_Workflow/scripts/compute_model_bounds_and_sizes.py",
    "Combination_Automotive_Diesel_Facility_Project/Python_Workflow/scripts/print_step_components.py",
]


def fetch_patch_text(url: str) -> str:
    # use stdlib to avoid extra deps
    try:
        # Python 3
        from urllib.request import urlopen

        with urlopen(url) as fh:
            raw = fh.read()
            return raw.decode("utf-8", errors="replace")
    except Exception as exc:  # pragma: no cover - network
        raise SystemExit(f"Failed to fetch patch: {exc}")


HUNK_RE = re.compile(r"^@@ -\d+(?:,\d+)? \+(\d+)(?:,(\d+))? @@")
DIFF_RE = re.compile(r"^diff --git a/(.+?) b/(.+)$")


def parse_hunks(
    patch_text: str, targets: List[str]
) -> Dict[str, List[Tuple[int, int]]]:
    anchors: Dict[str, List[Tuple[int, int]]] = {t: [] for t in targets}
    current: str | None = None
    targets_set = set(targets)
    for line in patch_text.splitlines():
        m = DIFF_RE.match(line)
        if m:
            # b_path is the new filename in the patch
            current = m.group(2)
            if current not in targets_set:
                current = None
            continue
        if current is None:
            continue
        m2 = HUNK_RE.match(line)
        if m2:
            start = int(m2.group(1))
            count = int(m2.group(2)) if m2.group(2) else 1
            end = start + count - 1
            anchors[current].append((start, end))
    return anchors


def write_md(anchors: Dict[str, List[Tuple[int, int]]], out_path: pathlib.Path) -> None:
    lines: List[str] = []
    lines.append("# PR: Per-hunk jump anchors")
    lines.append("")
    lines.append(
        "This file was generated by `.github/parse_pr_patch_hunks.py`. Each bullet links to the changed hunk range for reviewer convenience."
    )
    lines.append("")
    total = 0
    for path, hunks in anchors.items():
        if not hunks:
            continue
        lines.append(f"- **{path}**:")
        for i, (s, e) in enumerate(hunks, start=1):
            total += 1
            # GitHub file line anchors use path#Lstart-Lend
            lines.append(f"  - Hunk {i}: [{path}]({path}#L{s}-L{e})")
        lines.append("")
    if total == 0:
        lines.append("No hunks found for the configured target files.")
        lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path}")


def main(argv: List[str] | None = None) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--pr", type=int, default=DEFAULT_PR, help="PR number to fetch")
    p.add_argument(
        "--url", type=str, default=None, help="Direct patch URL (overrides --pr)"
    )
    p.add_argument(
        "--out",
        type=str,
        default=".github/pr_body_with_hunks.md",
        help="Output markdown path",
    )
    args = p.parse_args(argv)

    if args.url:
        url = args.url
    else:
        url = f"https://patch-diff.githubusercontent.com/raw/{DEFAULT_OWNER}/{DEFAULT_REPO}/pull/{args.pr}.patch"

    print(f"Fetching patch from: {url}")
    text = fetch_patch_text(url)
    anchors = parse_hunks(text, TARGET_FILES)
    write_md(anchors, pathlib.Path(args.out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
